export const setupRis28GHz = {
    title: "AI-based Communication Prototype with a 2304-element RIS of 28 GHz @ Tsinghua",
    description: "This prototype integrates a 2304-element RIS and an AI-based end-to-end architecture, which operates at 28 GHz. With the directional beam generated by RIS, the signal coverage is extended. In addition, an end-to-end system is trained off-line and deployed on the FPGA, which makes the constellation deviate from the traditional QAM structure.",
    images: [
        { src: "/assets/images/photos/mmWave-prototype.png", desc: "28 GHz RIS with 2304 elements" },
        { src: "/assets/images/photos/mmWave-test.jpg", desc: "Demo test in Tsinghua University, China" },
        { src: "/assets/images/photos/mmWave-RISTA.jpg", desc: "Demo session of RISTA @ Hangzhou, China" }
    ]
};
